get_property(IN_TRY_COMPILE GLOBAL PROPERTY IN_TRY_COMPILE)
if(IN_TRY_COMPILE OR GENERIC_GNU_ASM_INCLUDED)
	return()
endif()
set(GENERIC_GNU_ASM_INCLUDED TRUE)

set(CMAKE_ASM_OUTPUT_EXTENSION .o)
set(CMAKE_EXECUTABLE_SUFFIX_ASM .elf)
